# Generated by Django 2.0.7 on 2020-05-12 14:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cityinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cityinfo',
                'db_table': 'city_information',
                'ordering': ['population'],
            },
            managers=[
                ('citymanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
