# Generated by Django 2.0.7 on 2020-05-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0003_stateinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countryinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=7, null=True)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Country info',
                'db_table': 'country_information',
                'ordering': ['code'],
            },
        ),
    ]
