# Generated by Django 2.0.7 on 2020-05-13 08:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0004_countryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('director', models.CharField(max_length=50)),
                ('releasedate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Movies info',
                'db_table': 'movies_list',
                'ordering': ['releasedate'],
            },
            managers=[
                ('movieslist', django.db.models.manager.Manager()),
            ],
        ),
    ]
