# Generated by Django 2.0.7 on 2020-05-22 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0005_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(default=datetime.datetime(2020, 5, 22, 14, 37, 41, 365617)),
        ),
    ]
