# Generated by Django 2.0.7 on 2020-05-22 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0006_auto_20200522_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 3, 31, 65677)),
        ),
    ]
