# Generated by Django 2.0.7 on 2020-06-05 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0007_auto_20200522_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vichel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='Images/Vichel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='press ctl and select more authors', to='Bookstore.Author', verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='book name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(verbose_name='number of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 17, 25, 21, 67800), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.Publisher', verbose_name='publisher name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(verbose_name='rating'),
        ),
    ]
