# Generated by Django 2.0.7 on 2020-06-05 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0008_auto_20200605_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 17, 50, 56, 870585), verbose_name='published date'),
        ),
    ]
