# Generated by Django 2.0.7 on 2020-06-05 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0010_auto_20200605_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 20, 8, 48, 99984), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='vichel',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vichel',
            name='image',
            field=models.ImageField(upload_to='Images/Vichel'),
        ),
        migrations.AlterField(
            model_name='vichel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
