# Generated by Django 2.0.7 on 2020-06-18 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0012_auto_20200618_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 11, 21, 49, 731322), verbose_name='published date'),
        ),
    ]
