# Generated by Django 2.0.7 on 2020-04-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='dist',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='mandal',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='village',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
