# Generated by Django 2.0.7 on 2020-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0004_auto_20200429_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=21),
        ),
    ]
