# Generated by Django 2.0.7 on 2020-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0007_auto_20200429_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(blank=True, max_length=21),
        ),
    ]
