# Generated by Django 2.0.7 on 2020-04-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0010_auto_20200430_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
