# Generated by Django 2.0.7 on 2020-04-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0011_auto_20200430_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Efname', models.CharField(max_length=21)),
                ('Elname', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Onboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practice.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='Techgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gname', models.CharField(max_length=21)),
                ('employes', models.ManyToManyField(through='Practice.Onboard', to='Practice.Employe')),
            ],
        ),
        migrations.AddField(
            model_name='onboard',
            name='grp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practice.Techgroup'),
        ),
    ]
