# Generated by Django 2.0.7 on 2020-04-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0012_auto_20200430_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name'], 'verbose_name': 'first name'},
        ),
    ]
