# Generated by Django 2.0.7 on 2020-04-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0013_auto_20200430_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['-first_name'], 'verbose_name': 'Musician model'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name'], 'verbose_name': 'Person model'},
        ),
    ]
