# Generated by Django 2.0.7 on 2020-04-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0014_auto_20200430_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-state'], 'verbose_name': 'Address model'},
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album model'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['instrument'], 'verbose_name_plural': 'Musician model'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='album',
            order_with_respect_to='musician',
        ),
    ]
