# Generated by Django 2.0.7 on 2020-04-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0015_auto_20200430_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name_plural': 'Customer model'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['Pname'], 'verbose_name_plural': 'Pizza model'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['Tname'], 'verbose_name': 'Topping model'},
        ),
    ]
