# Generated by Django 2.0.7 on 2020-04-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0017_auto_20200430_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'get_latest_by': ['name'], 'verbose_name_plural': 'Customer model'},
        ),
    ]
