# Generated by Django 2.0.7 on 2020-04-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0018_auto_20200430_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Cgroup', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'student_info',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
