# Generated by Django 2.0.7 on 2020-04-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0019_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name_plural': 'Student model'},
        ),
    ]
