# Generated by Django 2.0.7 on 2020-05-01 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0021_mypeople_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Author Model',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Blog Model',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField()),
                ('authors', models.ManyToManyField(to='Practice.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practice.Blog')),
            ],
            options={
                'verbose_name_plural': 'Entry Model',
                'ordering': ['pub_date'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.AlterModelOptions(
            name='mypeople',
            options={'ordering': ['f_name'], 'verbose_name': 'Mypeople model'},
        ),
    ]
