# Generated by Django 2.0.7 on 2020-05-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Practice', '0022_auto_20200501_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='framework',
            name='frame_lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Practice.Language'),
        ),
    ]
